export {default as Home} from './Home'
export {default as About} from './About'
export {default as Class} from './Class'
export {default as Login} from '../components/User/Login'
export {default as Register} from '../components/User/Register'