export {default as Home} from './Home'
export {default as About} from './About'
export {default as Class} from './Class'
export {default as Login} from './Login'
export {default as Register} from './Register'